# Generated by Django 3.0.2 on 2020-04-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200416_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='movie',
            field=models.ManyToManyField(related_name='peoples', to='api.Movie'),
        ),
    ]
